defmodule JidoCode.GithubIssueBot.PullRequest.Workers.Actions.PRSubmitAction do
  @moduledoc """
  Creates the pull request on GitHub.

  Submits the fix branch as a pull request with appropriate metadata.

  ## Input

  - run_id: The parent run identifier
  - issue: Map with :title, :body, :repo, :number, etc.
  - triage: Triage results with :classification
  - research: Research findings from the research phase

  ## Output

  Emits pr_submit.result to parent with:
  - pr_number: The PR number
  - pr_url: URL to the pull request
  - title: PR title
  - summary: PR description/body

  ## Current Behavior (Stub)

  Returns mock PR data with generated title and URL.
  Planned: integrate with GitHub API to create actual PRs.
  """
  use Jido.Action,
    name: "pr_submit",
    schema: [
      run_id: [type: :string, required: true],
      issue: [type: :map, required: true],
      triage: [type: :map, required: true],
      research: [type: :map, required: true],
      patch: [type: :map, default: %{}],
      quality: [type: :map, default: %{}],
      attempt: [type: :integer, default: 1]
    ]

  alias Jido.Agent.Directive
  alias Jido.Signal

  require Logger

  def run(params, context) do
    run_id = params.run_id
    issue = params.issue
    triage = params.triage
    research = params.research
    patch = params.patch
    attempt = params.attempt

    Logger.debug("Creating PR for run: #{run_id} (after #{attempt} attempt(s))")

    issue_number = Map.get(issue, :number, 0)
    repo = Map.get(issue, :repo, "owner/repo")

    # Use branch from patch result if available
    branch_name = Map.get(patch, :branch_name, "fix/issue-#{issue_number}")

    # Stub: Generate mock PR data.
    # Planned: replace with actual GitHub API calls.
    pr_number = generate_pr_number()

    result = %{
      pr_number: pr_number,
      pr_url: "https://github.com/#{repo}/pull/#{pr_number}",
      title: generate_title(issue, triage),
      body: generate_body(issue, triage, research, attempt),
      branch: branch_name,
      labels: generate_labels(triage),
      draft: false,
      attempts: attempt,
      summary: "Pull request created successfully"
    }

    result_signal =
      Signal.new!(
        "pr_submit.result",
        %{
          run_id: run_id,
          worker_type: :pr_submit,
          result: result
        },
        source: "/pr_submit_agent"
      )

    emit_directive = Directive.emit_to_parent(%{state: context.state}, result_signal)

    {:ok,
     %{
       status: :completed,
       run_id: run_id,
       issue_number: issue_number
     }, List.wrap(emit_directive)}
  end

  # Generate a mock PR number
  defp generate_pr_number do
    :rand.uniform(9999) + 1000
  end

  # Generate PR title based on issue and classification
  defp generate_title(issue, triage) do
    issue_title = Map.get(issue, :title, "issue")
    classification = Map.get(triage, :classification, :unknown)

    case classification do
      :bug -> "Fix: #{issue_title}"
      :feature -> "Feat: #{issue_title}"
      :documentation -> "Docs: #{issue_title}"
      :performance -> "Perf: #{issue_title}"
      _ -> "Chore: #{issue_title}"
    end
  end

  # Generate PR body with context
  defp generate_body(issue, triage, research, attempt) do
    issue_number = Map.get(issue, :number, 0)
    classification = Map.get(triage, :classification, :unknown)
    root_cause = get_in(research, [:root_cause, :hypothesis]) || "See research findings"

    attempt_note =
      if attempt > 1,
        do: "\n\n> **Note**: This fix required #{attempt} iterations to pass all quality checks.",
        else: ""

    """
    ## Summary

    This PR addresses issue ##{issue_number}.#{attempt_note}

    ## Classification

    Type: #{classification}

    ## Root Cause Analysis

    #{root_cause}

    ## Changes Made

    - Implemented fix based on research findings
    - Added/updated tests
    - Updated documentation as needed

    ## Testing

    - [x] Unit tests pass
    - [x] Lint checks pass
    - [x] Type checks pass

    ---
    *This PR was automatically generated by the GitHub Issue Bot.*
    """
  end

  # Generate labels based on classification
  defp generate_labels(triage) do
    classification = Map.get(triage, :classification, :unknown)

    base_labels = ["bot-generated"]

    type_label =
      case classification do
        :bug -> "bug"
        :feature -> "enhancement"
        :documentation -> "documentation"
        :performance -> "performance"
        _ -> "maintenance"
      end

    [type_label | base_labels]
  end
end
