defmodule JidoCode.Repo.Migrations.AddProjectsResource do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:projects, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :github_full_name, :text, null: false
      add :default_branch, :text, null: false, default: "main"
      add :settings, :map, null: false, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:projects, [:github_full_name],
             name: "projects_unique_github_full_name_index"
           )
  end

  def down do
    drop_if_exists unique_index(:projects, [:github_full_name],
                     name: "projects_unique_github_full_name_index"
                   )

    drop table(:projects)
  end
end
