defmodule AgentJido.Repo.Migrations.CreateGithubDomain do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:github_webhook_deliveries, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :github_delivery_id, :text, null: false
      add :event_type, :text, null: false
      add :action, :text
      add :payload, :map, null: false
      add :status, :text, null: false, default: "pending"
      add :error_message, :text
      add :processed_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :watched_repo_id, :uuid, null: false
    end

    create table(:github_repos, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:github_webhook_deliveries) do
      modify :watched_repo_id,
             references(:github_repos,
               column: :id,
               name: "github_webhook_deliveries_watched_repo_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create unique_index(:github_webhook_deliveries, [:github_delivery_id],
             name: "github_webhook_deliveries_unique_github_delivery_index"
           )

    alter table(:github_repos) do
      add :owner, :text, null: false
      add :name, :text, null: false
      add :full_name, :text, null: false
      add :webhook_secret, :text, null: false
      add :webhook_id, :bigint
      add :enabled, :boolean, null: false, default: true
      add :settings, :map, default: %{}
      add :github_app_installation_id, :bigint

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "github_repos_user_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create unique_index(:github_repos, [:full_name], name: "github_repos_unique_full_name_index")

    create table(:github_issue_analyses, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :issue_number, :bigint, null: false
      add :issue_url, :text, null: false
      add :title, :text, null: false
      add :body, :text
      add :status, :text, null: false, default: "pending"
      add :original_labels, {:array, :text}, default: []
      add :suggested_labels, {:array, :text}, default: []
      add :applied_labels, {:array, :text}, default: []
      add :priority, :text
      add :complexity, :text
      add :assignee_recommendation, :text
      add :analysis_summary, :text
      add :raw_llm_response, :map
      add :labels_applied, :boolean, null: false, default: false
      add :comment_posted, :boolean, null: false, default: false
      add :analyzed_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :watched_repo_id,
          references(:github_repos,
            column: :id,
            name: "github_issue_analyses_watched_repo_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :webhook_delivery_id,
          references(:github_webhook_deliveries,
            column: :id,
            name: "github_issue_analyses_webhook_delivery_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create unique_index(:github_issue_analyses, [:watched_repo_id, :issue_number],
             name: "github_issue_analyses_unique_issue_per_repo_index"
           )
  end

  def down do
    drop_if_exists unique_index(:github_issue_analyses, [:watched_repo_id, :issue_number],
                     name: "github_issue_analyses_unique_issue_per_repo_index"
                   )

    drop constraint(:github_issue_analyses, "github_issue_analyses_watched_repo_id_fkey")

    drop constraint(:github_issue_analyses, "github_issue_analyses_webhook_delivery_id_fkey")

    drop table(:github_issue_analyses)

    drop_if_exists unique_index(:github_repos, [:full_name],
                     name: "github_repos_unique_full_name_index"
                   )

    drop constraint(:github_repos, "github_repos_user_id_fkey")

    alter table(:github_repos) do
      remove :user_id
      remove :updated_at
      remove :inserted_at
      remove :github_app_installation_id
      remove :settings
      remove :enabled
      remove :webhook_id
      remove :webhook_secret
      remove :full_name
      remove :name
      remove :owner
    end

    drop_if_exists unique_index(:github_webhook_deliveries, [:github_delivery_id],
                     name: "github_webhook_deliveries_unique_github_delivery_index"
                   )

    drop constraint(:github_webhook_deliveries, "github_webhook_deliveries_watched_repo_id_fkey")

    alter table(:github_webhook_deliveries) do
      modify :watched_repo_id, :uuid
    end

    drop table(:github_repos)

    drop table(:github_webhook_deliveries)
  end
end
