defmodule AgentJido.Repo.Migrations.AddForgeResources do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:github_webhook_deliveries) do
      remove :watched_repo_id

      add :repo_id,
          references(:github_repos,
            column: :id,
            name: "github_webhook_deliveries_repo_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    alter table(:github_issue_analyses) do
      remove :watched_repo_id

      add :repo_id,
          references(:github_repos,
            column: :id,
            name: "github_issue_analyses_repo_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    drop_if_exists unique_index(:github_issue_analyses, [:watched_repo_id, :issue_number],
                     name: "github_issue_analyses_unique_issue_per_repo_index"
                   )

    create unique_index(:github_issue_analyses, [:repo_id, :issue_number],
             name: "github_issue_analyses_unique_issue_per_repo_index"
           )

    create table(:forge_workflows, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :description, :text
      add :version, :bigint, default: 1
      add :steps, {:array, :map}, null: false
      add :timeout_ms, :bigint, default: 3_600_000
      add :on_error, :text, default: "halt"
      add :max_retries, :bigint, default: 0
      add :tags, {:array, :text}, default: []
      add :metadata, :map, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:forge_workflows, [:name], name: "forge_workflows_unique_name_index")

    create table(:forge_sprite_specs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :description, :text
      add :runner, :text, null: false
      add :runner_config, :map, default: %{}
      add :base_image, :text, default: "ubuntu-22.04"
      add :env, :map, default: %{}
      add :bootstrap_steps, {:array, :map}, default: []
      add :file_injection, {:array, :map}, default: []
      add :timeouts, :map
      add :resource_limits, :map, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:forge_sprite_specs, [:name],
             name: "forge_sprite_specs_unique_name_index"
           )

    create table(:forge_sessions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :session_id, :text, null: false
      add :sprite_id, :text
      add :runner, :text
      add :state, :text
      add :iteration, :bigint, default: 0
      add :spec_snapshot, :map, default: %{}
      add :last_activity_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:forge_sessions, [:session_id],
             name: "forge_sessions_unique_session_id_index"
           )
  end

  def down do
    drop_if_exists unique_index(:forge_sessions, [:session_id],
                     name: "forge_sessions_unique_session_id_index"
                   )

    drop table(:forge_sessions)

    drop_if_exists unique_index(:forge_sprite_specs, [:name],
                     name: "forge_sprite_specs_unique_name_index"
                   )

    drop table(:forge_sprite_specs)

    drop_if_exists unique_index(:forge_workflows, [:name],
                     name: "forge_workflows_unique_name_index"
                   )

    drop table(:forge_workflows)

    drop_if_exists unique_index(:github_issue_analyses, [:repo_id, :issue_number],
                     name: "github_issue_analyses_unique_issue_per_repo_index"
                   )

    create unique_index(:github_issue_analyses, [:watched_repo_id, :issue_number],
             name: "github_issue_analyses_unique_issue_per_repo_index"
           )

    drop constraint(:github_issue_analyses, "github_issue_analyses_repo_id_fkey")

    alter table(:github_issue_analyses) do
      remove :repo_id

      add :watched_repo_id,
          references(:github_repos,
            column: :id,
            name: "github_issue_analyses_watched_repo_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    drop constraint(:github_webhook_deliveries, "github_webhook_deliveries_repo_id_fkey")

    alter table(:github_webhook_deliveries) do
      remove :repo_id

      add :watched_repo_id,
          references(:github_repos,
            column: :id,
            name: "github_webhook_deliveries_watched_repo_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end
  end
end
