defmodule JidoCode.Repo.Migrations.AddWorkflowRunsResource do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:workflow_runs, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:run_id, :text, null: false)
      add(:workflow_name, :text, null: false)
      add(:workflow_version, :bigint, null: false)
      add(:status, :text, null: false, default: "pending")
      add(:trigger, :map, null: false, default: %{})
      add(:inputs, :map, null: false, default: %{})
      add(:input_metadata, :map, null: false, default: %{})
      add(:initiating_actor, :map, null: false, default: %{})
      add(:current_step, :text, null: false, default: "unknown")
      add(:status_transitions, {:array, :map}, null: false, default: [])
      add(:step_results, :map, null: false, default: %{})
      add(:error, :map)
      add(:started_at, :utc_datetime_usec, null: false)
      add(:completed_at, :utc_datetime_usec)

      add(
        :project_id,
        references(:projects,
          column: :id,
          name: "workflow_runs_project_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create(
      unique_index(:workflow_runs, [:project_id, :run_id],
        name: "workflow_runs_unique_run_per_project_index"
      )
    )

    create(
      index(:workflow_runs, [:project_id, :inserted_at],
        name: "workflow_runs_project_inserted_at_index"
      )
    )

    create(
      index(:workflow_runs, [:status, :inserted_at],
        name: "workflow_runs_status_inserted_at_index"
      )
    )
  end

  def down do
    drop_if_exists(
      index(:workflow_runs, [:status, :inserted_at],
        name: "workflow_runs_status_inserted_at_index"
      )
    )

    drop_if_exists(
      index(:workflow_runs, [:project_id, :inserted_at],
        name: "workflow_runs_project_inserted_at_index"
      )
    )

    drop_if_exists(
      unique_index(:workflow_runs, [:project_id, :run_id],
        name: "workflow_runs_unique_run_per_project_index"
      )
    )

    drop(table(:workflow_runs))
  end
end
