defmodule AgentJido.Repo.Migrations.MigrateResources1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    rename table(:github_webhook_deliveries), :watched_repo_id, to: :repo_id

    drop constraint(:github_webhook_deliveries, "github_webhook_deliveries_watched_repo_id_fkey")

    alter table(:github_webhook_deliveries) do
      modify :repo_id,
             references(:github_repos,
               column: :id,
               name: "github_webhook_deliveries_repo_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:github_issue_analyses, "github_issue_analyses_watched_repo_id_fkey")

    drop_if_exists unique_index(:github_issue_analyses, [:watched_repo_id, :issue_number],
                     name: "github_issue_analyses_unique_issue_per_repo_index"
                   )

    rename table(:github_issue_analyses), :watched_repo_id, to: :repo_id

    alter table(:github_issue_analyses) do
      modify :repo_id,
             references(:github_repos,
               column: :id,
               name: "github_issue_analyses_repo_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create unique_index(:github_issue_analyses, [:repo_id, :issue_number],
             name: "github_issue_analyses_unique_issue_per_repo_index"
           )
  end

  def down do
    drop_if_exists unique_index(:github_issue_analyses, [:repo_id, :issue_number],
                     name: "github_issue_analyses_unique_issue_per_repo_index"
                   )

    drop constraint(:github_issue_analyses, "github_issue_analyses_repo_id_fkey")

    alter table(:github_issue_analyses) do
      modify :repo_id,
             references(:github_repos,
               column: :id,
               name: "github_issue_analyses_watched_repo_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    rename table(:github_issue_analyses), :repo_id, to: :watched_repo_id

    create unique_index(:github_issue_analyses, [:watched_repo_id, :issue_number],
             name: "github_issue_analyses_unique_issue_per_repo_index"
           )

    drop constraint(:github_webhook_deliveries, "github_webhook_deliveries_repo_id_fkey")

    alter table(:github_webhook_deliveries) do
      modify :repo_id,
             references(:github_repos,
               column: :id,
               name: "github_webhook_deliveries_watched_repo_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    rename table(:github_webhook_deliveries), :repo_id, to: :watched_repo_id
  end
end
