defmodule AgentJido.Repo.Migrations.ForgeV2Resources do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:forge_sessions) do
      remove :spec_snapshot
      remove :iteration
      remove :state
      remove :runner
      remove :session_id
      modify :id, :uuid, default: fragment("uuid_generate_v7()")
      add :name, :text, null: false
      add :phase, :text, null: false, default: "created"
      add :runner_type, :text, null: false, default: "shell"
      add :runner_config, :map, default: %{}
      add :runner_state, :map, default: %{}
      add :spec, :map, default: %{}
      add :sprite_name, :text
      add :last_checkpoint_id, :text
      add :execution_count, :bigint, default: 0
      add :output_buffer, :text
      add :last_error, :map
      add :metadata, :map, default: %{}
      add :started_at, :utc_datetime_usec
      add :completed_at, :utc_datetime_usec
    end

    drop_if_exists unique_index(:forge_sessions, [:session_id],
                     name: "forge_sessions_unique_session_id_index"
                   )

    create unique_index(:forge_sessions, [:name], name: "forge_sessions_unique_name_index")

    create table(:forge_exec_sessions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :sequence, :bigint, null: false
      add :status, :text, null: false, default: "started"
      add :command, :text
      add :exit_code, :bigint
      add :output, :text
      add :output_size_bytes, :bigint, default: 0
      add :error, :map
      add :cost_usd, :decimal
      add :duration_ms, :bigint
      add :sprites_session_id, :text
      add :metadata, :map, default: %{}

      add :started_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :completed_at, :utc_datetime_usec

      add :session_id,
          references(:forge_sessions,
            column: :id,
            name: "forge_exec_sessions_session_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create table(:forge_events, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :event_type, :text, null: false
      add :data, :map, default: %{}
      add :exec_session_sequence, :bigint

      add :timestamp, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :session_id,
          references(:forge_sessions,
            column: :id,
            name: "forge_events_session_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create index(:forge_events, [:event_type])

    create index(:forge_events, [:session_id, :timestamp])

    create table(:forge_checkpoints, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :sprites_checkpoint_id, :text, null: false
      add :name, :text
      add :exec_session_sequence, :bigint
      add :runner_state_snapshot, :map
      add :metadata, :map, default: %{}

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :session_id,
          references(:forge_sessions,
            column: :id,
            name: "forge_checkpoints_session_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end
  end

  def down do
    drop constraint(:forge_checkpoints, "forge_checkpoints_session_id_fkey")

    drop table(:forge_checkpoints)

    drop constraint(:forge_events, "forge_events_session_id_fkey")

    drop_if_exists index(:forge_events, [:session_id, :timestamp])

    drop_if_exists index(:forge_events, [:event_type])

    drop table(:forge_events)

    drop constraint(:forge_exec_sessions, "forge_exec_sessions_session_id_fkey")

    drop table(:forge_exec_sessions)

    drop_if_exists unique_index(:forge_sessions, [:name],
                     name: "forge_sessions_unique_name_index"
                   )

    create unique_index(:forge_sessions, [:session_id],
             name: "forge_sessions_unique_session_id_index"
           )

    alter table(:forge_sessions) do
      remove :completed_at
      remove :started_at
      remove :metadata
      remove :last_error
      remove :output_buffer
      remove :execution_count
      remove :last_checkpoint_id
      remove :sprite_name
      remove :spec
      remove :runner_state
      remove :runner_config
      remove :runner_type
      remove :phase
      remove :name
      modify :id, :uuid, default: fragment("gen_random_uuid()")
      add :session_id, :text, null: false
      add :runner, :text
      add :state, :text
      add :iteration, :bigint, default: 0
      add :spec_snapshot, :map, default: %{}
    end
  end
end
